export const dropData = [
  {
    id: 1,
    img: "https://res.cloudinary.com/dpokiomqq/image/upload/v1673084428/Rectangle_82_cc3kxf.png",
    button: "upcoming",
    title: "Time remaining",
    time: "06  hrs : 45 min : 22 s",
    date: "November 21 at 11 am WAT",
    event: "Eyo : Eko For Show",
    text: "Lorem ipsum dolor sit amet consectetur. Amet odio a aenean quis vitae tempus. Sed nunc tempus aliquet lectus ut vulputate.",
    creator: "Aliya Minat",
    prompt: "Get notified",
  },
  {
    id: 2,
    img: "https://res.cloudinary.com/dpokiomqq/image/upload/v1673084432/Rectangle_84_irxgh2.png",
    button: "live now",
    title: "Time remaining",
    time: "06  hrs : 45 min : 22 s",
    date: "November 21 at 11 am WAT",
    event: "Ginger Suburbs",
    text: "Lorem ipsum dolor sit amet consectetur. Amet odio a aenean quis vitae tempus. Sed nunc tempus aliquet lectus ut vulputate.",
    creator: "Tina Grace",
    prompt: "Join now",
  },
  {
    id: 3,
    img: "https://res.cloudinary.com/dpokiomqq/image/upload/v1673084425/Rectangle_87_kbxcpb.png",
    button: "Ended",
    title: "Auction ended",
    time: "2 hours ago",
    date: "November 21 at 11 am WAT",
    event: "Sink",
    text: "Lorem ipsum dolor sit amet consectetur. Amet odio a aenean quis vitae tempus. Sed nunc tempus aliquet lectus ut vulputate.",
    creator: "Aliyat Minat",
    prompt: "View",
  },
  {
    id: 4,
    img: "https://res.cloudinary.com/dpokiomqq/image/upload/v1673084426/Rectangle_275_nwaqec.png",
    button: "Ended",
    title: "Auction ended",
    time: "5 hours ago",
    date: "November 21 at 11 am WAT",
    event: "Warped ‘99",
    text: "Lorem ipsum dolor sit amet consectetur. Amet odio a aenean quis vitae tempus. Sed nunc tempus aliquet lectus ut vulputate.",
    creator: "Aliyat Minat",
    prompt: "View",
  },
];